version: 2.1

jobs:
  # using tox
  toxify:
      docker:
        - image: quay.io/python-devs/ci-image
      steps:
        - checkout
        - run: pip install tox && tox

workflows:
  version: 2

  myproj:
    jobs:
      - toxify
