version: 2.1

jobs:
  # using tox
  toxify:
      docker:
        - image: quay.io/python-devs/ci-image:master
      steps:
        - checkout
        - run: ls -ltr
        - run: pwd
        - run: pip3 install tox
        - run: tox
        - store_test_results

workflows:
  version: 2

  myproj:
    jobs:
      - toxify
