version: 2.1

jobs:
  # using tox
  toxify:
      docker:
        - image: python:3.6
      steps:
        - checkout
        - run: pip install tox && tox

workflows:
  version: 2

  myproj:
    jobs:
          - hello/hello-build